import * as path from "node:path";
import * as vscode from "vscode";
import { SectionKey, SectionState } from "../models";
import { ScaffoldStorage } from "../storage";

export class SectionGateItem extends vscode.TreeItem {
  public readonly section: SectionKey;

  public constructor(section: SectionKey, label: string, state: SectionState, summaryText: string) {
    super(`${label} Gate`, vscode.TreeItemCollapsibleState.None);
    this.section = section;
    this.id = `section-gate:${section}`;

    const readOnly = section === "readyToBuild";
    const readOnlySuffix = readOnly ? " • Read-only • Auto-generated by Copilot" : "";
    this.description = `${state.status.toLowerCase()} · ${summaryText}${readOnlySuffix}`;

    if (state.status === "APPROVED") {
      this.iconPath = new vscode.ThemeIcon("check");
      this.contextValue = "section.gate.approved";
    } else if (state.status === "PENDING_REVIEW") {
      this.iconPath = new vscode.ThemeIcon("clock");
      this.contextValue = "section.gate.pending";
      this.command = {
        command: "scaffold.approveSection",
        title: "Approve Section",
        arguments: [section]
      };
    } else {
      this.iconPath = new vscode.ThemeIcon("lock");
      this.contextValue = "section.gate.locked";
    }
  }
}

export class SectionNodeItem extends vscode.TreeItem {
  public readonly uri: vscode.Uri;
  public readonly section: SectionKey;
  public readonly isDirectory: boolean;

  public constructor(uri: vscode.Uri, section: SectionKey, isDirectory: boolean, approved: boolean, requiresApproval: boolean) {
    super(
      path.basename(uri.path),
      isDirectory ? vscode.TreeItemCollapsibleState.Collapsed : vscode.TreeItemCollapsibleState.None
    );

    this.uri = uri;
    this.section = section;
    this.isDirectory = isDirectory;
    this.resourceUri = uri;

    // readyToBuild uses a separate contextValue prefix so rename/delete menus are suppressed
    const prefix = section === "readyToBuild" ? "readyToBuild" : "section";

    if (isDirectory) {
      this.contextValue = `${prefix}.folder`;
      this.iconPath = new vscode.ThemeIcon("folder");
      return;
    }

    this.command = {
      command: "vscode.open",
      title: "Open File",
      arguments: [uri]
    };

    if (!requiresApproval) {
      this.description = "";
      this.contextValue = `${prefix}.file.noapproval`;
      this.iconPath = new vscode.ThemeIcon("file");
      return;
    }

    this.description = approved ? "approved" : "pending";
    this.contextValue = approved ? `${prefix}.file.approved` : `${prefix}.file.pending`;
    this.iconPath = new vscode.ThemeIcon(approved ? "check" : "markdown");
  }
}

export type SectionTreeItem = SectionGateItem | SectionNodeItem;

export class SectionTreeProvider implements vscode.TreeDataProvider<SectionTreeItem> {
  private readonly onDidChangeTreeDataEmitter = new vscode.EventEmitter<SectionTreeItem | undefined>();
  public readonly onDidChangeTreeData = this.onDidChangeTreeDataEmitter.event;

  private activeProjectId: string | null = null;

  public constructor(
    private readonly storage: ScaffoldStorage,
    private readonly section: SectionKey
  ) {}

  public setActiveProject(projectId: string | null): void {
    this.activeProjectId = projectId;
    this.refresh();
  }

  public refresh(): void {
    this.onDidChangeTreeDataEmitter.fire(undefined);
  }

  public getTreeItem(element: SectionTreeItem): vscode.TreeItem {
    return element;
  }

  public async getChildren(element?: SectionTreeItem): Promise<SectionTreeItem[]> {
    if (!this.activeProjectId) {
      return [];
    }

    if (!element) {
      const rootEntries = await this.toNodeItems(this.activeProjectId, this.section);
      if (!this.storage.sectionHasGate(this.section)) {
        return rootEntries;
      }

      const state = await this.storage.getSectionState(this.activeProjectId, this.section);
      const summary = await this.storage.getSectionApprovalSummary(this.activeProjectId, this.section);
      const summaryText = `${summary.approvedFiles}/${summary.totalFiles} files approved`;
      const gate = new SectionGateItem(this.section, this.storage.getSectionDefinition(this.section).label, state, summaryText);
      return [gate, ...rootEntries];
    }

    if (element instanceof SectionNodeItem && element.isDirectory) {
      return this.toNodeItems(this.activeProjectId, this.section, element.uri);
    }

    return [];
  }

  private async toNodeItems(
    projectId: string,
    section: SectionKey,
    dirUri?: vscode.Uri
  ): Promise<SectionNodeItem[]> {
    const entries = await this.storage.listSectionEntries(projectId, section, dirUri);
    const mapped: SectionNodeItem[] = [];

    for (const entry of entries) {
      const isDirectory = entry.type === vscode.FileType.Directory;
      if (!isDirectory && !this.storage.isSupportedSectionFilePath(section, entry.uri.path)) {
        continue;
      }

      const requiresApproval = this.storage.sectionHasGate(section);
      const approved = !requiresApproval || isDirectory ? false : await this.storage.isFileApproved(projectId, section, entry.uri);
      mapped.push(new SectionNodeItem(entry.uri, section, isDirectory, approved, requiresApproval));
    }

    return mapped;
  }
}
